<a href="https://colab.research.google.com/github/Shellyga/Adversarial-Domain-Adaptation-with-Keras/blob/master/Check_new_implementation_adda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load images

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
SEED = 7
import os
import sys
import argparse
import random
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from plotnine import *
import pandas as pd
                
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from math import ceil
from sklearn.utils import shuffle as skshuffle

from imutils import paths
from sklearn.preprocessing import LabelEncoder

# os.environ['PYTHONHASHSEED']=str(SEED)
# np.random.seed(SEED)
# set_random_seed(SEED)
# random.seed(SEED)

from PIL import Image
from keras.utils import to_categorical
from keras.layers import Input
from keras.optimizers import Adam
from keras.utils import multi_gpu_model
from sklearn.metrics import accuracy_score
import pickle

NUM_CLASSES = 0


def pil_loader(path):
    # print(path)
    # Return the RGB variant of input image
    with open(path, 'rb') as f:
      with Image.open(f) as img:
        return img.convert('RGB')

def one_hot_encoding(param,labels):
    lb = LabelEncoder()
    fit_labels  = lb.fit_transform(labels)
    param["number_of_classe"] = len(lb.classes_) 
    labels = to_categorical(fit_labels)
    f = open('drive/My Drive/pro_data/result_vgg_notBmix/labels',"wb")
    f.write(pickle.dumps(lb))
    f.close()
    return labels

            
def data_loader(filepath, inp_dims):
    # Load images and corresponding labels from the text file, stack them in numpy arrays and return
    # if not os.path.isfile(filepath):
    #     print("File path {} does not exist. Exiting...".format(filepath))
        # sys.exit() 
    img = []
    label = []
    detector = dlib.get_frontal_face_detector()
    predictor = "drive/My Drive/final_proj_dataset/shape_predictor_5_face_landmarks.dat"
    # grab the image paths
    imagePaths = sorted(list(paths.list_images(filepath)))
    print(imagePaths[0])
    # loop over the input images
    for imagePath in imagePaths:
        # extract the class label from the image path and update the
        # labels list
        l = imagePath.split(os.path.sep)[-2]
        label.append(l)
        i = pil_loader(imagePath)
        i = i.resize((inp_dims[0], inp_dims[1]), Image.ANTIALIAS)
        frame_1 = align_and_crop(detector, np.array(i), predictor)[0]
        frame_1 = cv2.resize(frame_1,(inp_dims[0], inp_dims[1]))
        img.append(frame_1)
    img, label = skshuffle(img, label)
    img = np.array(img)
    label = np.array(label)
    return img, label

def get_dataset(param,path):
      print("[INFO] loading images...")
      # Load source and target data
      X,y = data_loader(path, [224,224,3])
      print("images loaded")
      X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
      # Encode labels into one-hot format
      print("[INFO] Encode labels into one-hot format")
      y_train = one_hot_encoding(param,y_train)
      y_test = one_hot_encoding(param,y_test)
      return (X_train, y_train), (X_test, y_test)

Using TensorFlow backend.


# Crop

In [0]:
import dlib

import os
import sys
import cv2
import glob


def align_and_crop(detector, im_to_align, predictor_path):
    '''
    simply aligns the photo (using the detector to identify the eyes) and crops the face.
    :param im_to_align: an address of an image
    '''

    # a shape predictor to find face landmarks so we can precisely localize the face
    sp = dlib.shape_predictor(predictor_path)

    # Ask the detector to find the bounding boxes of each face. The 1 in the
    # second argument indicates that we should upsample the image 1 time.
    try:
        dets = detector(im_to_align, 1)
    except RuntimeError:
        return -1

    num_faces = len(dets)
    if num_faces == 0:
        return im_to_align, False

    # Find the 5 face landmarks we need to do the alignment.
    faces = dlib.full_object_detections()
    for detection in dets:
        faces.append(sp(im_to_align, detection))

    # get a single chip (aligned and cropped)
    image = dlib.get_face_chip(im_to_align, faces[0])
    # cv2.imshow("f", image) show image for testing
    return image, True

# optimizer

In [0]:
import numpy as np
from keras.optimizers import Adam

def opt_classifier(param):
    return Adam(lr=param["lr_classifier"], beta_1=param["b1_classifier"], beta_2=param["b2_classifier"])

def opt_discriminator(param):
    return Adam(lr=param["lr_discriminator"], beta_1=param["b1_discriminator"], beta_2=param["b2_discriminator"])



# ADDA

In [5]:
pip install keras_vggface

In [0]:

from keras.layers import Input, Dense, Reshape, Flatten, Dropout
from keras.layers import BatchNormalization, Activation
from keras.layers.advanced_activations import LeakyReLU
from keras.layers.convolutional import UpSampling2D, Conv2D
from keras.models import Sequential, Model, clone_model
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import Adam

import keras
from keras.utils import np_utils

import tensorflow.compat.v1 as tf
# from datasets import get_dataset

import matplotlib.pyplot as plt

import sys
import os
import numpy as np
import argparse
from keras_vggface.vggface import VGGFace

In [0]:
def define_source_encoder():

        inp = Input(shape= param["inp_dims"])
        network = eval('VGGFace')
        base = network(weights = 'vggface', include_top = False)
        # base = network(model = 'resnet50',weights = 'vggface', include_top = False)
        param["source_encoder"] = Model(inp,base(inp))

def define_target_encoder():
       param["target_encoder"] = clone_model(param["source_encoder"])

def get_source_classifier(model):
        
    x = Flatten()(model.output)
    # dense1 = Dense(400, name = 'class_dense1')(x)
    # bn1 = BatchNormalization(name = 'class_bn1')(dense1)
    # act1 = Activation('relu', name = 'class_act1')(bn1)
    # drop2 = Dropout(param["drop_classifier"], name = 'class_drop1')(act1)

    # dense2 = Dense(100, name = 'class_dense2')(drop2)
    # bn2 = BatchNormalization(name = 'class_bn2')(dense2)
    # act2 = Activation('relu', name = 'class_act2')(bn2)
    # drop2 = Dropout(param["drop_classifier"], name = 'class_drop2')(act2)
    # densel = Dense(param["number_of_classe"], name = 'class_dense_last')(drop2)

    densel = Dense(param["number_of_classe"], name = 'class_dense_last')(x)
    bnl = BatchNormalization(name = 'class_bn_last')(densel)
    actl = Activation('softmax', name = 'class_act_last')(bnl)
        
    source_classifier_model = Model(inputs=(model.input), outputs=(actl))
        
    return source_classifier_model

def define_discriminator(shape):
        
    inp = Input(shape=shape)
    x = Flatten()(inp)
    # dense1 = Dense(400, name = 'dis_dense1')(x)
    # bn1 = BatchNormalization(name='dis_bn1')(dense1)
    # act1 = Activation('relu', name = 'dis_act1')(bn1)
    # drop1 = Dropout(param["drop_discriminator"], name = 'dis_drop1')(act1)

    # dense2 = Dense(100, name = 'dis_dense2')(drop1)
    # bn2 = BatchNormalization(name='dis_bn2')(dense2)
    # act2 = Activation('relu', name = 'dis_act2')(bn2)
    # drop2 = Dropout(param["drop_discriminator"], name = 'dis_drop2')(act2)
    # densel = Dense(1, name = 'dis_dense_last')(drop2)

    densel = Dense(1, name = 'dis_dense_last')(x)
    bnl = BatchNormalization(name = 'dis_bn_last')(densel)
    actl = Activation('sigmoid', name = 'dis_act_last')(bnl)
    param["discriminator_model"] = Model(inputs=(inp), outputs=(actl), name='discriminator')

def get_discriminator(model):    
    disc = Model(inputs=(model.input), outputs=(param["discriminator_model"](model.output)))
    return disc

  

In [0]:
def train_source_model(param, epochs=4, batch_size=64, save_interval=1, start_epoch=0):

        (train_x, train_y), (test_x, test_y) = param["source_data_train"], param["source_data_test"]
        datagen = ImageDataGenerator(data_format='channels_last', 
                                rescale=1./255, 
                                rotation_range=40, 
                                width_shift_range=0.2, 
                                height_shift_range=0.2)
       
        evalgen = ImageDataGenerator(data_format='channels_last', 
                                rescale=1./255)
        
        param["source_model"].compile(optimizer = opt_classifier(param), loss = 'categorical_crossentropy', metrics = ['accuracy'])

        param["source_model"].fit_generator(datagen.flow(train_x, train_y, batch_size=batch_size, shuffle=True),
                            steps_per_epoch=100, 
                            epochs=epochs, 
                            validation_data=evalgen.flow(test_x[:100], test_y[:100], batch_size=batch_size), 
                            initial_epoch=start_epoch)
        
        param["source_model"].save('drive/My Drive/pro_data/result_vgg_notBmix/_source_model_less_layers.h5')

        y_pred = param["source_model"].predict(test_x[100:])
        source_accuracy_test = accuracy_score(test_y[100:].argmax(1), y_pred.argmax(1))              

        print("source accuracy test",source_accuracy_test)
        print("Source Classifier matrix: ",metrics.confusion_matrix(test_y[100:].argmax(1), y_pred.argmax(1)))

In [0]:
import keras.backend as K
def train_target_discriminator(param, epochs=3, batch_size=64, save_interval=30, start_epoch=0, num_batches=120):   
    
        (source_x, _), (_,_) = param["source_data_train"], param["source_data_test"]
        
        src_datagen = ImageDataGenerator(data_format='channels_last', 
                                rescale=1./255, 
                                rotation_range=40, 
                                width_shift_range=0.2, 
                                height_shift_range=0.2)
        
        (target_x, _), (_,_) = param["target_data_train"], param["target_data_test"]
        
        tgt_datagen = ImageDataGenerator(data_format='channels_last', 
                                rescale=1./255, 
                                rotation_range=40, 
                                width_shift_range=0.2, 
                                height_shift_range=0.2)
        
        # define_source_encoder()
        define_target_encoder()
        define_discriminator(param["source_encoder"].output_shape[1:])
                
        for layer in param["source_encoder"].layers:
            layer.trainable = False
        
        param["source_dicriminator"] = get_discriminator(param["source_encoder"])
        param["target_dicriminator"]= get_discriminator(param["target_encoder"])
        
        
        param["source_dicriminator"].compile(optimizer = opt_discriminator(param), loss = 'binary_crossentropy', metrics = ['accuracy'])
        param["target_dicriminator"].compile(optimizer = opt_discriminator(param), loss = 'binary_crossentropy', metrics = ['accuracy'])
        
        src_names = ['src_discriminator_loss', 'src_discriminator_acc']
        tgt_names = ['tgt_discriminator_loss', 'tgt_discriminator_acc']
        
        for iteration in range(start_epoch, epochs):
            
            avg_loss, avg_acc, index = [0, 0], [0, 0], 0

            for source,target in zip(src_datagen.flow(source_x, None, batch_size=batch_size), tgt_datagen.flow(target_x, None, batch_size=batch_size)):
                # s_domain = np_utils.to_categorical(np.zeros(source.shape[0]), 1)
                # t_domain =  np_utils.to_categorical(np.ones(target.shape[0]), 1)
                s_domain = np.zeros(source.shape[0])
                t_domain =  np.ones(target.shape[0])
                l1, acc1 = param["source_dicriminator"].train_on_batch(source,s_domain )
                l2, acc2 = param["target_dicriminator"].train_on_batch(target,t_domain)
                index+=1
                loss, acc = (l1+l2)/2, (acc1+acc2)/2
                print (iteration+1,': ', index,'/', num_batches, '; Loss: %.4f'%loss, ' (', '%.4f'%l1, '%.4f'%l2, '); Accuracy: ', acc, ' (', '%.4f'%acc1, '%.4f'%acc2, ')')
                avg_loss[0] += l1
                avg_acc[0] += acc1
                avg_loss[1] += l2
                avg_acc[1] += acc2
                if index%num_batches == 0:
                    break

            # if iteration%param["discriminator_decay_rate"]==0:
            #     param["lr_s"] = K.get_value(source_discriminator.optimizer.lr)
            #     K.set_value(source_discriminator.optimizer.lr, lr*self.discriminator_decay_factor)
            #     lr = K.get_value(target_discriminator.optimizer.lr)
            #     K.set_value(target_discriminator.optimizer.lr, lr*self.discriminator_decay_factor)
            #     print ('Learning Rate Decayed to: ', K.get_value(target_discriminator.optimizer.lr))
            if iteration%save_interval==0:
                  param["source_dicriminator"].save_weights('drive/My Drive/pro_data/result_vgg_notBmix/4classes_discriminator_s_weights_%02d.hdf5'%iteration)
                  param["target_dicriminator"].save_weights('drive/My Drive/pro_data/result_vgg_notBmix/4classe_discriminator_t_weights_%02d.hdf5'%iteration)
                  param["target_encoder"].save_weights('drive/My Drive/pro_data/result_vgg_notBmix/4classe_encoder_t_weights_%02d.hdf5'%iteration)
        
        param["source_dicriminator"].save_weights('drive/My Drive/pro_data/result_vgg_notBmix/4classes_discriminator_s_weights_less_layrs.hdf5')
        param["target_dicriminator"].save_weights('drive/My Drive/pro_data/result_vgg_notBmix/4classe_discriminator_t_weights_less_layrs.hdf5')
        param["target_encoder"].save_weights('drive/My Drive/pro_data/result_vgg_notBmix/4classe_encoder_t_weights_less_layrs.hdf5')


        
            
            
            


In [0]:
def eval_source_classifier( param,  model,batch_size=128, domain='Source'):
      
        (train_x,_), (test_x, test_y) = param["target_data_train"], param["target_data_test"]
        src_datagen = ImageDataGenerator(data_format='channels_last', 
                                        rescale=1./255)
                      
        model.compile(optimizer = opt_classifier(param), loss = 'categorical_crossentropy', metrics = ['accuracy'])


        scores = model.evaluate_generator(src_datagen.flow(test_x, test_y),1000)
        print(' %s Classifier Test loss:%.5f'%( domain, scores[0]))
        print(' %s Classifier Test accuracy:%.2f%%'%( domain, float(scores[1])*100))            
            
def eval_target_classifier(param):
        
        param["target_encoder"].summary()
        model = get_source_classifier(param["target_encoder"])
        # path_target_discriminator = 'drive/My Drive/pro_data/result_vgg_notBmix/4classe_discriminator_t_weights.hdf5'
        # path_target_discriminator = 'drive/My Drive/pro_data/result_vgg/discriminator_t_weights.hdf5'
        path_target_discriminator = 'drive/My Drive/pro_data/result_vgg_notBmix/4classe_discriminator_t_weights_less_layrs.hdf5'
        model.load_weights(path_target_discriminator, by_name=True)
        model.summary()
        eval_source_classifier(param,  model, domain='Target')

In [0]:
import argparse
if __name__ == "__main__":
    # Read parameter values from the console
    parser = argparse.ArgumentParser(description = 'Domain Adaptation')
    parser.add_argument('--number_of_gpus', type = int, nargs = '?', default = '1', help = "Number of gpus to run")
    parser.add_argument('--network_name', type = str, default = 'ResNet50', help = "Name of the feature extractor network")
    parser.add_argument('--dataset_name', type = str, default = 'Office', help = "Name of the source dataset")
    parser.add_argument('--dropout_classifier', type = float, default = 0.25, help = "Dropout ratio for classifier")
    parser.add_argument('--dropout_discriminator', type = float, default = 0.25, help = "Dropout ratio for discriminator")    
    parser.add_argument('--source_path', type = str, default = 'amazon_10_list.txt', help = "Path to source dataset")
    parser.add_argument('--target_path', type = str, default = 'webcam_10_list.txt', help = "Path to target dataset")
    parser.add_argument('--lr_classifier', type = float, default = 0.0001, help = "Learning rate for classifier model")
    parser.add_argument('--b1_classifier', type = float, default = 0.9, help = "Exponential decay rate of first moment \
                                                                                             for classifier model optimizer")
    parser.add_argument('--b2_classifier', type = float, default = 0.999, help = "Exponential decay rate of second moment \
                                                                                            for classifier model optimizer")
    parser.add_argument('--lr_discriminator', type = float, default = 0.00001, help = "Learning rate for discriminator model")
    parser.add_argument('--b1_discriminator', type = float, default = 0.9, help = "Exponential decay rate of first moment \
                                                                                             for discriminator model optimizer")
    parser.add_argument('--b2_discriminator', type = float, default = 0.999, help = "Exponential decay rate of second moment \
                                                                                            for discriminator model optimizer")
    parser.add_argument('--lr_combined', type = float, default = 0.00001, help = "Learning rate for combined model")
    parser.add_argument('--b1_combined', type = float, default = 0.9, help = "Exponential decay rate of first moment \
                                                                                             for combined model optimizer")
    parser.add_argument('--b2_combined', type = float, default = 0.999, help = "Exponential decay rate of second moment \
                                                                                            for combined model optimizer")
    parser.add_argument('--classifier_loss_weight', type = float, default = 1, help = "Classifier loss weight")
    parser.add_argument('--discriminator_loss_weight', type = float, default = 4, help = "Discriminator loss weight")
    parser.add_argument('--batch_size', type = int, default = 32, help = "Batch size for training")
    parser.add_argument('--test_interval', type = int, default = 3, help = "Gap between two successive test phases")
    parser.add_argument('--num_iterations', type = int, default = 120, help = "Number of iterations")
    parser.add_argument('--snapshot_interval', type = int, default = 500, help = "Minimum gap between saving outputs")
    parser.add_argument('--output_dir', type = str, default = 'Models', help = "Directory for saving outputs")
    # args = parser.parse_args()

    # Set GPU device
    # os.environ["CUDA_VISIBLE_DEVICES"] = str(list(np.arange(args.number_of_gpus))).strip('[]')

    # Initialize parameters
    param = {}
    param["number_of_gpus"] = 1
    # param["network_name"] = 'ResNet50'
    param["network_name"] = 'VGGFace'
    param["inp_dims"] = [224, 224, 3]
    param["num_iterations"] = 10000
    # param["num_iterations"] = 500
    param["lr_classifier"] = 0.0001
    param["b1_classifier"] = 0.9
    param["b2_classifier"] = 0.999    
    param["lr_discriminator"] = 0.00001
    param["b1_discriminator"] =  0.9
    param["b2_discriminator"] = 0.999
    param["lr_combined"] = 0.00001
    param["b1_combined"] =  0.9
    param["b2_combined"] =  0.999       
    # param["batch_size"] = int(32)
    param["batch_size"] = int(32/2)
    param["class_loss_weight"] = 1
    param["dis_loss_weight"] = 4    
    param["drop_classifier"] = 0.25
    param["drop_discriminator"] = 0.25
    param["test_interval"] = 100
    # param["source_path"] = 'drive/My Drive/final_proj_dataset/data_file_shelly.txt'
    # param["target_path"] = 'drive/My Drive/final_proj_dataset/data_file_yerus.txt' 
    param["source_path"] = '/content/drive/My Drive/pro_data/‏‏‏‏source_notBmix'
    param["target_path"] = '/content/drive/My Drive/pro_data/‏‏‏‏target_notBmix' 
    param["snapshot_interval"] = 500
    # param["snapshot_interval"] = 5
    param["output_path"] = 'drive/My Drive/pro_data/result_vgg_notBmix'
    param["number_of_classe"] = 0

    # Create directory for saving models and log files
    if not os.path.exists(param["output_path"]):
        os.mkdir(param["output_path"])

    # param["source_encoder"] = None
    # param["target_encoder"] = None
    # param["target_dicriminator"] = None
    # param["source_dicriminator"] = None
    # param["discriminator_model"] = None

    # param["source_data_train"], param["source_data_test"] = get_dataset(param["source_path"])
    # param["target_data_train"], param["target_data_test"] = get_dataset(param["target_path"])


    # # model = get_source_classifier(param["source_encoder"])
    # # train_source_model(model, start_epoch-1)
    # train_target_discriminator(param)
    # # model = get_source_classifier(param["source_encoder"])
    # # train_source_model(model, start_epoch-1)
    # eval_target_classifier(param)
    # # model = get_source_classifier(param["source_encoder"])
    # # eval_source_classifier(model, 'drive/My Drive/pro_data/dataset_shelly')
    # # eval_source_classifier(model, 'drive/My Drive/pro_data/dataset_yerus')
    
    
    
    

   

In [13]:
    param["source_data_train"], param["source_data_test"] = get_dataset(param,param["source_path"])
    param["target_data_train"], param["target_data_test"] = get_dataset(param,param["target_path"])
    print(param["number_of_classe"] )


[INFO] loading images...
/content/drive/My Drive/pro_data/‏‏‏‏source_notBmix/brows/IMG_B1_SHELLY-396.jpg
images loaded
[INFO] Encode labels into one-hot format
[INFO] loading images...
/content/drive/My Drive/pro_data/‏‏‏‏target_notBmix/brows/IMG_BROWS_YERUS-1007.jpg
images loaded
[INFO] Encode labels into one-hot format
4


In [0]:
define_source_encoder()
# define_target_encoder()

In [26]:

param["source_model"] = get_source_classifier(param["source_encoder"])
train_source_model(param)

Epoch 1/4
100/100 [==============================] - 183s 2s/step - loss: 0.6490 - accuracy: 0.8097 - val_loss: 0.7940 - val_accuracy: 0.9400
Epoch 2/4
100/100 [==============================] - 168s 2s/step - loss: 0.3842 - accuracy: 0.9566 - val_loss: 0.5123 - val_accuracy: 0.9600
Epoch 3/4
100/100 [==============================] - 168s 2s/step - loss: 0.3503 - accuracy: 0.9638 - val_loss: 0.4076 - val_accuracy: 0.9500
Epoch 4/4
100/100 [==============================] - 168s 2s/step - loss: 0.3339 - accuracy: 0.9696 - val_loss: 0.2152 - val_accuracy: 0.9500
source accuracy test 0.9850746268656716
Source Classifier matrix:  [[38  0  0  0]
 [ 0 56  0  0]
 [ 4  0 80  0]
 [ 0  0  0 90]]


In [27]:
test_x,test_y = param["target_data_test"]
y_pred = param["source_model"].predict(test_x)
target_accuracy_test = accuracy_score(test_y.argmax(1), y_pred.argmax(1))              

print("Target accuracy test",target_accuracy_test)
print("Target Classifier matrix: ",metrics.confusion_matrix(test_y.argmax(1), y_pred.argmax(1)))

Target accuracy test 0.5161290322580645
Target Classifier matrix:  [[  3   0  59  19]
 [  0   6   4  70]
 [  0   0 102   6]
 [  0   0  22  81]]


In [0]:
eval_source_classifier( param,  param["source_model"])

 Source Classifier Test loss:1.31252
 Source Classifier Test accuracy:39.11%


In [0]:
param["source_model"].save('drive/My Drive/pro_data/result_vgg_notBmix/source_model_4_classes.h5')
# loaded_model = load_model('drive/My Drive/pro_data/result_vgg/model.h5')

In [28]:
train_target_discriminator(param)

1 :  1 / 120 ; Loss: 0.7454  ( 0.7976 0.6932 ); Accuracy:  0.59375  ( 0.5781 0.6094 )
1 :  2 / 120 ; Loss: 0.7469  ( 0.8007 0.6932 ); Accuracy:  0.4921875  ( 0.4688 0.5156 )
1 :  3 / 120 ; Loss: 0.7455  ( 0.7978 0.6932 ); Accuracy:  0.5234375  ( 0.5938 0.4531 )
1 :  4 / 120 ; Loss: 0.7455  ( 0.7978 0.6932 ); Accuracy:  0.546875  ( 0.5625 0.5312 )
1 :  5 / 120 ; Loss: 0.7455  ( 0.7979 0.6932 ); Accuracy:  0.546875  ( 0.5625 0.5312 )
1 :  6 / 120 ; Loss: 0.7437  ( 0.7942 0.6932 ); Accuracy:  0.515625  ( 0.4688 0.5625 )
1 :  7 / 120 ; Loss: 0.7438  ( 0.7944 0.6932 ); Accuracy:  0.546875  ( 0.5156 0.5781 )
1 :  8 / 120 ; Loss: 0.7450  ( 0.7969 0.6932 ); Accuracy:  0.546875  ( 0.6094 0.4844 )
1 :  9 / 120 ; Loss: 0.7458  ( 0.7985 0.6932 ); Accuracy:  0.5234375  ( 0.5156 0.5312 )
1 :  10 / 120 ; Loss: 0.7430  ( 0.7928 0.6932 ); Accuracy:  0.515625  ( 0.5312 0.5000 )
1 :  11 / 120 ; Loss: 0.7459  ( 0.7986 0.6932 ); Accuracy:  0.4765625  ( 0.4531 0.5000 )
1 :  12 / 120 ; Loss: 0.7459  ( 0.7986

In [29]:
test_x,test_y = param["target_data_test"]
param["target_encoder"].summary()
model = get_source_classifier(param["target_encoder"])
path_target_discriminator = 'drive/My Drive/pro_data/result_vgg_notBmix/4classe_discriminator_t_weights_less_layrs.hdf5'
model.load_weights(path_target_discriminator, by_name=True)
y_pred = model.predict(test_x)
 
target_accuracy_test = accuracy_score(test_y.argmax(1), y_pred.argmax(1))              

print("Target accuracy test",target_accuracy_test)
print("Target Classifier matrix: ",metrics.confusion_matrix(test_y.argmax(1), y_pred.argmax(1)))

Model: "model_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
vggface_vgg16 (Model)        multiple                  14714688  
Total params: 14,714,688
Trainable params: 14,714,688
Non-trainable params: 0
_________________________________________________________________
Target accuracy test 0.3064516129032258
Target Classifier matrix:  [[44  0 29  8]
 [23  0 13 44]
 [14  0 40 54]
 [ 7  0 66 30]]


In [0]:
param["target_dicriminator"].save_weights('drive/My Drive/pro_data/result_vgg_notBmix/discriminator_t_weights.hdf5')
param["target_encoder"].save_weights('drive/My Drive/pro_data/result_vgg_notBmix/encoder_t_weights.hdf5')


In [32]:
eval_target_classifier(param)

Model: "model_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
vggface_vgg16 (Model)        multiple                  14714688  
Total params: 14,714,688
Trainable params: 14,714,688
Non-trainable params: 0
_________________________________________________________________
Model: "model_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
vggface_vgg16 (Model)        multiple                  14714688  
_________________________________________________________________
flatten_8 (Flatten)          (None, 25088)             0         
_____________________________

# Use for loadede models

In [0]:
define_source_encoder()
define_target_encoder()

test_xt,test_yt = param["target_data_test"]
path_source_classifier = ''
classifier = model.load(path_source_classifier)

y_pred = classifier.predict(test_xt)
target_accuracy_test = accuracy_score(test_y.argmax(1), y_pred.argmax(1))              

print("Target accuracy test with source classifier",target_accuracy_test)
print("Target Classifier matrix: ",metrics.confusion_matrix(test_yt.argmax(1), y_pred.argmax(1)))

path_target_discriminator = 'drive/My Drive/pro_data/result_vgg_notBmix/4classe_discriminator_t_weights.hdf5'
model.load_weights(path_target_discriminator, by_name=True)

yt_pred = classifier.predict(test_xt)
target_accuracy_test = accuracy_score(test_y.argmax(1), yt_pred.argmax(1))              

print("Target accuracy test with target classifier",target_accuracy_test)
print("Target Classifier matrix: ",metrics.confusion_matrix(test_yt.argmax(1), yt_pred.argmax(1)))

# Save target classifier

In [0]:
import keras
path_source_classifier = 'drive/My Drive/pro_data/result_vgg_notBmix/_source_model_less_layers.h5'
classifier = keras.models.load_model(path_source_classifier)

path_target_discriminator = 'drive/My Drive/pro_data/result_vgg_notBmix/4classe_discriminator_t_weights_less_layrs.hdf5'
classifier.load_weights(path_target_discriminator, by_name=True)

classifier.save('drive/My Drive/pro_data/result_vgg_notBmix/4classe_target_classifier_less_layrs.hdf5')